config/routes.rb
Spree::Core::Engine.routes.draw do
  # The route name inspirez-vous should be configurable
  get '/:taxon/inspirez-vous', to: 'lookbooks#index', as: :lookbooks
  get '/:taxon/inspirez-vous/:slug', to: 'lookbooks#show', as: :show_lookbook
  get '/:taxon//inspirez-vous/:slug/:kit', to: 'kits#show', as: :show_kit


  namespace :admin do
    get '/kits/add_product/', to: 'kits#add_product'
    get '/lookbooks/kits/add_product/', to: 'lookbooks/kits#add_product'
    get '/lookbooks/add_kit/', to: 'lookbooks#add_kit'



    concern :positionable do
      collection do
        post :update_positions
      end
    end

    resources :kits    do
      collection do
        get :search
      end
    end

    resources :lookbooks, concerns: :positionable do
      resources :kits, concerns: :positionable, controller: "lookbooks/kits" do
        post "update_product_position", to: "lookbooks/kits#update_product_positions", as: :update_product_position
      end
      post "edit", to: "lookbooks#edit order"
    end
  end
end

app/models/kit.rb
module Spree
  class Kit < Spree::Base
    has_many :spree_kit_product
    has_many :spree_kit_lookbook
    has_many :spree_products, :through => 'spree_kit_product'
    has_many :spree_lookbooks, :through => 'spree_kit_lookbook'

    translates :name, presence: true


    has_attached_file :image,

                      styles: { mini: '32x32>', normal: '128x128>', large: '1100x467>' },
                      default_style: :large,
                      path: '/:class/:id/:style/:basename.:extension',
                      default_url: '/assets/bebefille.jpg'


  end
end

app/models/spree/kit.rb
module Spree
  class Kit < Spree::Base
    extend FriendlyId

    has_many :spree_kits_products, -> { order(:position) }, class_name: "Spree::KitProduct"
    has_many :spree_kits_lookbooks, class_name: "Spree::KitLookbook"
    has_many :products, :through => 'spree_kits_products', class_name: "Spree::Product"
    has_many :lookbooks, :through => 'spree_kits_lookbooks', class_name: "Spree::Lookbook"

    translates :name, :image, :slug, presence: true
    accepts_nested_attributes_for :translations, :spree_kits_products, allow_destroy: true


    has_many :images
    friendly_id :slug_candidates, use: :globalize

    def slug_candidates
      [[:name]]
    end

    def image_for product, format = :large
      skp = spree_kits_products.find_by(product: product)
      if skp && skp.image?
         skp.image.url(format)
      else
        if product.images.empty?
          unless product.variants.joins(:images).any?
            return "noimage/product.png"
          end
          return product.variants.joins(:images).first.images.first.attachment.url(format)
        else
          image = product.images.first
          image.attachment.url(format)
        end
      end
    end

    class Translation
      belongs_to :spree_kit
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    end

  end
end

app/models/spree/lookbook.rb
module Spree
  class Lookbook < ActiveRecord::Base
    extend FriendlyId

    has_many :images


    has_many :spree_kits_lookbooks, -> { order(:position) }, class_name: "Spree::KitLookbook"

    has_many :kits, :through => 'spree_kits_lookbooks', class_name: "Spree::Kit"




    belongs_to :spree_taxon,  class_name: "Spree::Taxon"
    translates :name, :image, :slug, presence: true

    accepts_nested_attributes_for :translations, :spree_kits_lookbooks, allow_destroy: true

    friendly_id :slug_candidates, use: :globalize

    def slug_candidates
      [[:name],[:name, :id]]
    end

    class Translation
      belongs_to :spree_lookbook
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    end



  end
end

app/controllers/spree/admin/kits_controller.rb
module Spree
  module Admin
    class KitsController < ResourceController
      respond_to :js, only: [:add_product]
      respond_to :json

      def index
        @kits = Spree::Kit.all
      end

      #retourne un js qui pop une ligne dans un tableau
      def add_product
        @product = Spree::Product.find(params[:product_id])

        puts @product.inspect
        respond_to do |format|
          format.js {}
        end
      end

      def search
         @kits = Spree::Kit.with_translations.where("name like ?", "%"+params[:q][:name_cont]+"%")
         render json: {results: @kits}
      end

      def show
        @kits = Spree::Kit.find(params[:id])
      end

      def edit
        @kits = Spree::Kit.find(params[:id])
      end

      private
      def find_resource
        Spree::Kit.friendly.find(params[:id])
      end
    end
  end
end

app/controllers/spree/admin/lookbooks/kits_controller.rb
module Spree
  module Admin
    module Lookbooks
      class KitsController < ResourceController

        before_action :load_lookbook, except: :add_product
        respond_to :js, only: [:add_product]

        def index
          @kits = Spree::Kit.all
        end

        def new
          @lookbooks_kit = Kit.new
        end

        def edit
          @lookbooks_kit = find_resource
        end

        #retourne un js qui pop une ligne dans un tableau
        def add_product
          @product = Spree::Product.find(params[:product_id])

          respond_to do |format|
            format.js {}
          end
        end

        def load_lookbook
          @lookbook = Lookbook.friendly.find(params[:lookbook_id])
        end

        def create
          @lookbooks_kit = Kit.new(permitted_resource_params)
          @lookbooks_kit.lookbooks << @lookbook
          @lookbooks_kit.save
        end

        def update_positions
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              @lookbook.spree_kit_lookbook.find_by(kit_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def update_product_positions
          @kit = Spree::Kit.friendly.find(params[:kit_id])
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              @kit.spree_kits_products.find_by(spree_product_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def find_resource
          Spree::Kit.friendly.find(params[:id])
        end

        private
        def model_class
          Spree::Kit
        end

        def permitted_resource_params
          params["kit"].present? ? params.require("kit").permit! : ActionController::Parameters.new
        end

        def location_after_save
          edit_admin_lookbook_path(@lookbook)
        end

        def find_resource

          if params[:id]
            Spree::Kit.friendly.find(params[:id])
          else
            Spree::Kit.friendly.find(params[:kit_id])

          end
        end

      end
    end
  end
end

app/controllers/spree/admin/lookbooks_controller.rb
module Spree
  module Admin
    class LookbooksController < ResourceController

      before_action :load_data, except: [:index, :new]


      def index
        @lookbooks = Spree::Lookbook.all
      end

      def load_data
        if params[:id]
         @lookbook = Spree::Lookbook.friendly.find(params[:id])
        else
          @lookbook = Spree::Lookbook.new unless @lookbook
        end
      end


      def new_kit
        @kit = Kit.new
         render( template: "spree/admin/lookbooks/kits/new", locals: {resource: @kit})
      end

      def add_kit
        @kit = Spree::Kit.find(params[:kit_id])

        respond_to do |format|
          format.js {}
        end


      end



      private
      def lookbook_params
        params.require(:lookbook).permit(:name, :taxon_id)
      end

      def find_resource
        if parent_data.present?
          parent.send(controller_name).friendly.find(params[:id])
        else
          model_class.friendly.find(params[:id])
        end
      end



    end
  end
end

app/controllers/spree/kits_controller.rb
module Spree
  class KitsController < Spree::StoreController
    respond_to :js, :html
    before_action :find_taxon
    def show

      if params[:slug]
        @lookbook = Spree::Lookbook.friendly.find(params[:slug])
      else
        @lookbook = Spree::Lookbook.joins(:kits).order(created_at: :desc).first
      end
      if params[:kit]
        @kit = @lookbook.kits.friendly.find(params[:kit])
      else
        @kit = @lookbook.kits.first
      end
    end

    private
    def find_taxon
      @taxon = Spree::Taxon.friendly.find(params[:taxon])
    end

  end
end

app/controllers/spree/lookbooks_controller.rb
module Spree
  class LookbooksController < Spree::StoreController
    respond_to :js, :html
    before_action :find_taxon
    def show
      if params[:slug]
        @lookbook = Spree::Lookbook.friendly.find(params[:slug])
      else
        @lookbook = Spree::Lookbook.joins(:kits).order(created_at: :desc).first
      end
        @kit = @lookbook.kits.first
    end

    def index
      @lookbooks = Spree::Lookbook.joins(:kits).where("spree_taxon_id"=> @taxon.self_and_descendants.pluck(:id) ).uniq
    end

    private
    def find_taxon
      @taxon = Spree::Taxon.friendly.find(params[:taxon])
    end
  end
end

app/views/spree/admin/lookbooks/kits/_form.html.erb
<div data-hook="admin_inside_kits_form">
  <div class="row">
    <div class="col-md-6">
      <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
          <%= f.text_field  :name, :class => 'form-control' %>
          <%= error_message_on :kit, :name, :class => 'error-message' %>
      <% end %>
    </div>


  </div>
  <div class="row">

      <div class="col-md-6">
        <%= f.field_container :product_ids, class: ['form-group'] do %>
            <%= f.label :product_ids, Spree.t('product_rule.choose_products') %> <span class="required">*</span>
            <%= hidden_field_tag :product_id, "", class: "product_picker", data: {
                                                    url: "/admin/lookbooks/kits/add_product",
                                                    remote: true }
            %>
            <%= error_message_on :kit, :product_ids, :class => 'error-message' %>
        <% end %>
      </div>
  </div>

  <% if f.object.persisted? %>

  <table class="table sortable" id = "product_table"  data-sortable-link="<%= admin_lookbook_kit_update_product_position_path(@lookbook, @lookbooks_kit) %>">
    <tr>
      <th class="no-border"></th>


      <th>
        <%= Spree.t("product_id") %>
      </th>
      <th>
        <%= Spree.t("product_name") %>
      </th>
      <th>
        <%= Spree.t("product_image") %>
      </th>
      <th></th>


    </tr>
    <% @lookbooks_kit.spree_kits_products.each do |skp| %>
        <% puts skp.product.inspect %>
        <%= render "product_line", {product: skp.product, skp: skp} %>
    <% end %>


  </table>

      <div class ='translationDiv'>
        <%= link_to_with_icon 'translate', nil, admin_translations_path('kits', f.object.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' %>
      </div>
  <% else %>
      <table class="table" id = "product_table" >
        <tr>
          <th class="no-border"></th>


          <th>
            <%= Spree.t("product_id") %>
          </th>
          <th>
            <%= Spree.t("product_name") %>
          </th>
          <th>
            <%= Spree.t("product_image") %>
          </th>

        </tr>
        <% @lookbooks_kit.spree_kits_products.each do |skp| %>
            <% next unless skp.product %>
            <%= render "product_line", {product: skp.product, skp: skp} %>
        <% end %>


      </table>
  <% end %>


</div>

app/views/spree/admin/lookbooks/kits/_product_line.html.erb
<% if defined?(product) && product %>

    <tr id="<%= spree_dom_id product %>" >
      <% line_id = (defined? skp )? skp : rand(500..500000) %>
      <td class="handle move-handle"><span class="icon icon-move handle"></span></td>


      <td>
      <% if defined?(skp) && skp %>
          <%= hidden_field_tag "kit[spree_kits_products_attributes][#{line_id}][id]", skp.id %>

    <% end %>
      <%= hidden_field_tag "kit[spree_kits_products_attributes][#{line_id}][spree_product_id]", product.id %>
        <%= hidden_field_tag "kit[spree_kits_products_attributes][#{line_id}][_destroy]", "false", data:{hook: "deleter"} %>

        <%= product.master.sku %>
    </td>
    <td>
      <%= product.name %>

    </td>

      <td>
        <% if (defined?(skp) && skp)  %>
            <%= image_tag skp.kit.image_for( skp.product, :normal) %>
        <% end %>
        <div class="panel-body">
          <%= file_field_tag "kit[spree_kits_products_attributes][#{line_id}][image]" , class: 'form-control', rows: 4 %>
        </div>
      </td>
      <td class="actions actions-2 text-right">
        <% if @lookbook %>
            <%= link_to_with_icon 'delete', "", "#remove_line", class: "btn btn-danger btn-sm deete-resource" %>
        <% end %>
      </td>
    </tr>
<% end %>

app/views/spree/admin/lookbooks/kits/add_product.js.erb
$("#product_table").append("<%= j (render "product_line", {product: @product}) %>");

$("#product_id").select2("val", "");

app/views/spree/admin/lookbooks/kits/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:kits_edit) %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_kits), spree.admin_kits_path, :icon => 'arrow-left' %>
    </li>
<% end %>



<div id="ajax_error" class="errorExplanation" style="display:none;"></div>

<%= form_for [:admin, @lookbooks_kit], url: admin_lookbook_kit_path(@lookbook, @lookbooks_kit), multipart: true do |f| %>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <fieldset class="no-border-top">
      <br>
      <div class="filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'ok' %>
      </div>
    </fieldset>


<% end %>

app/views/spree/admin/lookbooks/kits/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:kits) %>
<% end %>

<% content_for :page_actions do %>
    <span id="new_ot_link">
      <%= button_link_to Spree.t(:new_kit), spree.new_admin_kit_path, { :icon => 'SS', :id => 'admin_new_kit', :class => 'btn-success' } %>
    </span>
<% end %>


<% if @kits.any? %>

    <table class="table sortable" id="listing-store-locations data-hook">
      <thead>
      <tr data-hook="option_header">
        <th><%= Spree.t(:kit) %></th>
        <th class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @kits.each do |kit| %>
          <tr id="<%= spree_dom_id kit %>">
            <td class="presentation"><%= kit.name %></td>
            <td class="actions actions-2 text-right">
              <%= link_to_edit(kit.id, class: 'admin_edit_option_type', no_text: true) %>
              <%= link_to_delete(kit, no_text: true) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::SizingChart)) %>,
      <%= link_to Spree.t(:add_one), new_admin_kit_path %>!
    </div>
<% end %>

app/views/spree/admin/lookbooks/kits/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:kit) %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_kits), spree.admin_lookbook_kits_path(@lookbook), :icon => 'arrow-left' %>
    </li>
<% end %>

<%= form_for [:admin, @lookbooks_kit], url: admin_lookbook_kits_path(@lookbook) do |f| %>

    <%= render :partial => 'spree/admin/lookbooks/kits/form', :locals => { :f => f } %>

    <fieldset class="no-border-top">
      <br>
      <div class="filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:create), 'ok' %>
      </div>
    </fieldset>

<% end %>