config/routes.rb
Spree::Core::Engine.routes.draw do
  # The route name inspirez-vous should be configurable
  get '/:taxon/inspirez-vous', to: 'lookbooks#index', as: :lookbooks
  get '/:taxon/inspirez-vous/:slug', to: 'lookbooks#show', as: :show_lookbook
  get '/:taxon//inspirez-vous/:slug/:kit', to: 'kits#show', as: :show_kit


  namespace :admin do
    get '/kits/add_product/', to: 'kits#add_product'
    get '/lookbooks/kits/add_product/', to: 'lookbooks/kits#add_product'
    get '/lookbooks/add_kit/', to: 'lookbooks#add_kit'



    concern :positionable do
      collection do
        post :update_positions
      end
    end

    resources :kits    do
      collection do
        get :search
      end
    end

    resources :lookbooks, concerns: :positionable do
      resources :kits, concerns: :positionable, controller: "lookbooks/kits" do
        post "update_product_position", to: "lookbooks/kits#update_product_positions", as: :update_product_position
      end
      post "edit", to: "lookbooks#edit order"
    end
  end
end

app/models/spree/kit.rb
module Spree
  class Kit < Spree::Base
    extend FriendlyId

    has_many :spree_kits_products, -> { order(:position) }, class_name: "Spree::KitProduct"
    has_many :spree_kits_lookbooks, class_name: "Spree::KitLookbook"
    has_many :products, :through => 'spree_kits_products', class_name: "Spree::Product"
    has_many :lookbooks, :through => 'spree_kits_lookbooks', class_name: "Spree::Lookbook"

    translates :name, :image, :slug, presence: true
    accepts_nested_attributes_for :translations, :spree_kits_products, allow_destroy: true


    has_many :images
    friendly_id :slug_candidates, use: :globalize

    def slug_candidates
      [[:name]]
    end

    def image_for product, format = :large
      skp = spree_kits_products.find_by(product: product)
      if skp && skp.image?
         skp.image.url(format)
      else
        if product.images.empty?
          unless product.variants.joins(:images).any?
            return "noimage/product.png"
          end
          return product.variants.joins(:images).first.images.first.attachment.url(format)
        else
          image = product.images.first
          image.attachment.url(format)
        end
      end
    end

    class Translation
      belongs_to :spree_kit
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    end

  end
end

app/models/spree/kit_lookbook.rb
module Spree
  class KitLookbook < Spree::Base
    self.table_name = "spree_kits_lookbooks"
    acts_as_list
    belongs_to :kit, class_name: "Spree::Kit"
    belongs_to :lookbook, class_name: "Spree::Lookbook"
  end
end

app/models/spree/kit_product.rb
module Spree
  class KitProduct < Spree::Base
    self.table_name = "spree_kits_products"

    acts_as_list
    belongs_to :kit, class_name: "Spree::Kit"
    belongs_to :product, class_name: "Spree::Product", foreign_key: "spree_product_id"

    has_attached_file :image,

                      styles: { mini: '32x32>', normal: '128x128>', product: '240x240>', large: '600x600>' },
                      default_style: :large
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  end
end

app/models/spree/lookbook.rb
module Spree
  class Lookbook < ActiveRecord::Base
    extend FriendlyId

    has_many :images


    has_many :spree_kits_lookbooks, -> { order(:position) }, class_name: "Spree::KitLookbook"

    has_many :kits, :through => 'spree_kits_lookbooks', class_name: "Spree::Kit"




    belongs_to :spree_taxon,  class_name: "Spree::Taxon"
    translates :name, :image, :slug, presence: true

    accepts_nested_attributes_for :translations, :spree_kits_lookbooks, allow_destroy: true

    friendly_id :slug_candidates, use: :globalize

    def slug_candidates
      [[:name],[:name, :id]]
    end

    class Translation
      belongs_to :spree_lookbook
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    end



  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  has_many :spree_kits_products, -> { order(:position) }, class_name: "Spree::KitProduct", foreign_key: "spree_product_id"
  has_many :kits, :through => 'spree_kits_products', class_name: "Spree::Kit"

  def with_similar_kit
    products = []
    no_kit = kits.count
    if no_kit == 0 then
      return products
    end
    rand_kit = Random.rand(no_kit)

    tids = self.taxons.where("#{Spree::Taxon.table_name}.taxonomy_id = 2").leaves.pluck(:id)

    kit_products = Spree::Product
                       .joins(:kits)
                       .where('spree_products.id != ?', self.id)
                       .where('spree_kits.id = ?', kits.offset(rand_kit).pluck(:id)[0]).uniq

    kit_products.each do |kp|
      to_add = true
      tids.each do |id|
        if kp.taxon_ids.include? id
          puts "Product #{kp.id} has taxon #{id} DO NOT ADD"
          to_add = false
        end
      end
      products << kp if to_add
    end
    return products.shuffle

  end

end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_many :lookbooks,foreign_key: "spree_taxon_id"
end

app/controllers/spree/admin/kits_controller.rb
module Spree
  module Admin
    class KitsController < ResourceController
      respond_to :js, only: [:add_product]
      respond_to :json

      def index
        @kits = Spree::Kit.all
      end

      #retourne un js qui pop une ligne dans un tableau
      def add_product
        @product = Spree::Product.find(params[:product_id])

        puts @product.inspect
        respond_to do |format|
          format.js {}
        end
      end

      def search
         @kits = Spree::Kit.with_translations.where("name like ?", "%"+params[:q][:name_cont]+"%")
         render json: {results: @kits}
      end

      def show
        @kits = Spree::Kit.find(params[:id])
      end

      def edit
        @kits = Spree::Kit.find(params[:id])
      end

      private
      def find_resource
        Spree::Kit.friendly.find(params[:id])
      end
    end
  end
end

app/controllers/spree/admin/lookbooks/kits_controller.rb
module Spree
  module Admin
    module Lookbooks
      class KitsController < ResourceController

        before_action :load_lookbook, except: :add_product
        respond_to :js, only: [:add_product]

        def index
          @kits = Spree::Kit.all
        end

        def new
          @lookbooks_kit = Kit.new
        end

        def edit
          @lookbooks_kit = find_resource
        end

        #retourne un js qui pop une ligne dans un tableau
        def add_product
          @product = Spree::Product.find(params[:product_id])

          respond_to do |format|
            format.js {}
          end
        end

        def load_lookbook
          @lookbook = Lookbook.friendly.find(params[:lookbook_id])
        end

        def create
          @lookbooks_kit = Kit.new(permitted_resource_params)
          @lookbooks_kit.lookbooks << @lookbook
          @lookbooks_kit.save
        end

        def update_positions
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              @lookbook.spree_kit_lookbook.find_by(kit_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def update_product_positions
          @kit = Spree::Kit.friendly.find(params[:kit_id])
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              @kit.spree_kits_products.find_by(spree_product_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def find_resource
          Spree::Kit.friendly.find(params[:id])
        end

        private
        def model_class
          Spree::Kit
        end

        def permitted_resource_params
          params["kit"].present? ? params.require("kit").permit! : ActionController::Parameters.new
        end

        def location_after_save
          edit_admin_lookbook_path(@lookbook)
        end

        def find_resource

          if params[:id]
            Spree::Kit.friendly.find(params[:id])
          else
            Spree::Kit.friendly.find(params[:kit_id])

          end
        end

      end
    end
  end
end

app/controllers/spree/admin/lookbooks_controller.rb
module Spree
  module Admin
    class LookbooksController < ResourceController

      before_action :load_data, except: [:index, :new]


      def index
        @lookbooks = Spree::Lookbook.all
      end

      def load_data
        if params[:id]
         @lookbook = Spree::Lookbook.friendly.find(params[:id])
        else
          @lookbook = Spree::Lookbook.new unless @lookbook
        end
      end


      def new_kit
        @kit = Kit.new
         render( template: "spree/admin/lookbooks/kits/new", locals: {resource: @kit})
      end

      def add_kit
        @kit = Spree::Kit.find(params[:kit_id])

        respond_to do |format|
          format.js {}
        end


      end



      private
      def lookbook_params
        params.require(:lookbook).permit(:name, :taxon_id)
      end

      def find_resource
        if parent_data.present?
          parent.send(controller_name).friendly.find(params[:id])
        else
          model_class.friendly.find(params[:id])
        end
      end



    end
  end
end

app/controllers/spree/kits_controller.rb
module Spree
  class KitsController < Spree::StoreController
    respond_to :js, :html
    before_action :find_taxon
    def show

      if params[:slug]
        @lookbook = Spree::Lookbook.friendly.find(params[:slug])
      else
        @lookbook = Spree::Lookbook.joins(:kits).order(created_at: :desc).first
      end
      if params[:kit]
        @kit = @lookbook.kits.friendly.find(params[:kit])
      else
        @kit = @lookbook.kits.first
      end
    end

    private
    def find_taxon
      @taxon = Spree::Taxon.friendly.find(params[:taxon])
    end

  end
end

app/controllers/spree/lookbooks_controller.rb
module Spree
  class LookbooksController < Spree::StoreController
    respond_to :js, :html
    before_action :find_taxon
    def show
      if params[:slug]
        @lookbook = Spree::Lookbook.friendly.find(params[:slug])
      else
        @lookbook = Spree::Lookbook.joins(:kits).order(created_at: :desc).first
      end
        @kit = @lookbook.kits.first
    end

    def index
      @lookbooks = Spree::Lookbook.joins(:kits).where("spree_taxon_id"=> @taxon.self_and_descendants.pluck(:id) ).uniq
    end

    private
    def find_taxon
      @taxon = Spree::Taxon.friendly.find(params[:taxon])
    end
  end
end

app/views/spree/shared/_kit.html.erb
<%= image_tag "noimage/large.png", {class: 'deferred_img section_header_banner', data:{original: @kit.image.url(:large) } } %>


<%
   paginated_products = @kit.products.page(params[:page]).per(12)
%>

<% if paginated_products.any? %>
    <div id="products" class="products-list clear">
      <% paginated_products.each do |product| %>
          <% url = spree.product_path(product) %>
          <div id="product_<%= product.id %>" class="products-list__single <%= cycle("alpha", "secondary", "", "omega secondary", :name => "classes") %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
            <% cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : [I18n.locale, current_currency, product]) do %>
                <div class="thumb clear">
                  <%= link_to t("taxons.preview"), url, class: 'btn_quickview' %>
                  <%= link_to image_tag(@kit.image_for(product), {:itemprop => "image", :lazy => true}), url, :itemprop => 'url', :class => 'link' %>
                </div>
                <h3><%= link_to truncate(product.name, :length => 50), url, :class => 'info', :itemprop => "name", :title => product.name %></h3>

                <% if product.respond_to?(:on_sale?) && product.on_sale? %>
                    <div class="price">
                      <span class="old-price"><%= display_original_price(product) %></span>
                      <span class="sale-price"><%= display_price(product) %></span>
                    </div>
                <% else %>
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                      <span class="price" itemprop="price"><%= display_price(product) %></span>
                    </div>
                <% end %>


            <% end %>
          </div>
      <% end %>
      <% reset_cycle("classes") %>

      <% if paginated_products.respond_to?(:num_pages) %>
          <%= paginate paginated_products %>
      <% end %>

    </div>

<% end %>

app/views/spree/shared/_lookbook_taxonomies.html.erb
<div id="accordion">
  <% cache [I18n.locale, @lookbook] do %>
      <ul class="menu-sidebar">
        <li class ="first__link">
          <ul class="menu-sidebar">
          <% @taxon.self_and_descendants.joins(:lookbooks).uniq.each do |t| %>
                <li class=" second__link"><%= link_to t.name, nested_taxons_path(t) %>
                  <ul class="menu-sidebar">

                  <% t.lookbooks.each do |l| %>
                        <li class="third__link"><%= link_to l.name, show_lookbook_path(l.slug)  %></li>
                  <% end %>
                  </ul>

                </li>

          <% end %>
        </li>
      </ul>
  <% end %>
</div>

app/views/spree/shared/_taxonomies.html.erb
<% if @taxon %>
    <% if Spree::Lookbook.joins(:kits).where("spree_taxon_id"=> @taxon.self_and_descendants.pluck(:id)).any?  %>


        <% cache [I18n.locale,"lookbook", @kit] do %>
            <ul class="menu-sidebar">
              <li class ="first__link">
                <div class="title">
                      <h2><%= raw t("lookbook") %></h2>
                </div>
                <ul class="menu-sidebar">
                  <li class=" second__link">


                  <ul class="menu-sidebar">

                  <% @taxon.self_and_descendants.joins(:lookbooks).uniq.each do |t| %>


                          <% t.lookbooks.each do |l| %>
                            <% l.kits.each do |k| %>
                              <li class="third__link <%= @lookbook == l && @kit == k ? "current" : "" %>" data-kit-li="<%=k.id %>"><%= link_to k.name, show_kit_path(@taxon, l.slug, k.slug)  %></li>
                            <% end %>
                        <% end %>

                  <% end %>
                        </ul>

                        </li>

                </ul>
              </li>
            </ul>
        <% end %>

    <% end %>



    <div id="accordion">
      <% cache [I18n.locale, @taxon] do %>
          <%= taxons_tree(@taxon.root, @taxon, 4) %>
      <% end %>
    </div>

<% else %>
    <%= render partial: 'spree/shared/filters' %>
<% end %>